### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by adeelibr** [withvoid/melting-pot#37]
Add a  `Pull request template` that tells the user what is the protocol for creating a pull request. You can take some content from the `Contributing.md` docs for this.

Reference: https://github.com/withvoid/melting-pot/blob/master/CONTRIBUTING.md

Things that the template should have

* format of the pull request title
* details description of what the pull request does
* reference to already open issue if any that is related to the pull request

**Comment by saniakjamil** [comment]
Can I take up this issue?
