### ISSUE TITLE
Add eslint plugin for React hooks

### ISSUE THREAD

**Issue by saniakjamil** [withvoid/melting-pot#41]
Please add eslint react hooks plugin to ensure enforcement of [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

npm package [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks), should be added.

**Comment by adeelibr** [comment]
Closing this issue & marking it as resolved because of #42
