### ISSUE TITLE
Demo not working on iPad Safari

### ISSUE THREAD

**Issue by saihaj** [withvoid/melting-pot#49]
![IMG_0064](https://user-images.githubusercontent.com/44710980/84104355-0e3c8280-a9db-11ea-9312-99333f17b08a.png)

**Comment by adeelibr** [comment]
@saihaj thank you for reporting this, I am labeling this as priority 1. Will be fixed todayl.

**Comment by adeelibr** [comment]
@saihaj the issue has been fixed, the site is up & live at https://melting-pot.netlify.app/

Thank you for reporting this issue.
