### ISSUE TITLE
[Feature] Add a new hook called useToggle

### ISSUE THREAD

**Issue by adeelibr** [withvoid/melting-pot#5]
Proposal for hook
```
const [on, set] = React.useState(initialState);
return { on, set, reset, toggle }; 
```

Where 
* on Boolean
* set Function
* reset Function (That resets to initial state)
* toggle Functions (That toggles the current state on <strong>on</strong>)

**Comment by afaqahmedkhan** [comment]
I'm working on this issue

**Comment by adeelibr** [comment]
@afaqahmedkhan Pull requests are always welcome and appreciated. Do let me know if you need help or if you get stuck anywhere. :)

**Comment by adeelibr** [comment]
Great PR 🤗
